### ISSUE TITLE
Its not Packet based

### ISSUE THREAD

**Issue by Snowiiii** [ch1ck3n-ovo/SalmonAC#6]
Hey i saw your Cool Anticheat Project, But Looking throw i saw its using Bukkit Events and not Packets as how the Readme implies ?

**Comment by ch1ck3n-ovo** [comment]
I think I used PacketEvent from Protocol in SalmonAC.java

**Comment by Snowiiii** [comment]
Ye this is the only thing your using Packets, But you should use Packets everywhere, For example Replacing EntityDamageEvent and more

**Comment by ch1ck3n-ovo** [comment]
Understood, I used my friend's anticheat base for this project and didn't think much lol

**Comment by Snowiiii** [comment]
great, when you need any help feel free to checkout my anticheat guide gist
